/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#000e24',
        'primary-container': '#00234b',
        'on-primary': '#ffffff',
        'on-primary-container': '#718bb9',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f8',
        secondary: '#516072',
        'secondary-container': '#d2e1f7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#556477',
        'secondary-fixed': '#d4e4fa',
        'secondary-fixed-dim': '#b9c8de',
        'on-secondary-fixed': '#0d1c2d',
        'on-secondary-fixed-variant': '#39485a',
        tertiary: '#220400',
        'tertiary-container': '#480f00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fb4c00',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59e',
        'on-tertiary-fixed': '#3a0b00',
        'on-tertiary-fixed-variant': '#852400',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#455f8a',
        'on-surface': '#191c1e',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#adc7f8',
        outline: '#74777f',
        'outline-variant': '#c4c6d0',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        base: '8px',
        gutter: '16px',
        'container-margin': '20px',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'price-lg': ['Space Grotesk', 'sans-serif'],
        'spec-label': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'price-lg': ['20px', { lineHeight: '1', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1', fontWeight: '600' }],
        'spec-label': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
